# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|

  config.vm.box = "wheezy64"
  config.vm.box_url = "http://vagrant.devile.net/debian_7.1_wheezy_64_m.box"

  config.vm.network :hostonly, "10.11.100.20"
  #config.vm.network :hostonly, "192.168.111.10"
  config.vm.host_name = "greenspace.dev.pedrocandeias.com"

  config.vm.share_folder "develop", "/project/greenspace2", "../", owner: "www-data", group: "www-data"

  # Use 384mb in the VM
  config.vm.customize ["modifyvm", :id, "--memory", "384"]

  # Use all available cpus in the VM
  config.vm.customize ["modifyvm", :id, "--cpus", `awk "/^processor/ {++n} END {print n}" /proc/cpuinfo 2> /dev/null || sh -c 'sysctl -n hw.logicalcpu 2> /dev/null' || echo 1`.chomp]
  #config.vm.customize ["modifyvm", :id, "--cpus", "1"]

  config.vm.customize ["modifyvm", :id, "--name", "greenspace.dev.pedrocandeias.com"]

  # Allow symlinks on shared folders
  config.vm.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
  config.vm.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/develop", "1"]

  config.vm.provision :shell, :inline => "sudo apt-get update"

  config.vm.provision :shell, :inline => 'echo -e "mysql_root_password=vagrantpassword controluser_password=awesome" > /etc/phpmyadmin.facts;'

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.module_path = "modules"
    puppet.options = "--verbose"
  end

end
