games_index:
    pattern: /games
    defaults: { _controller: MyMainBundle:Games:index }

games_show:
    pattern: /games/{game}
    defaults: { _controller: MyMainBundle:Games:show }

games_state:
    pattern: /games/{game}/state
    defaults: { _controller: MyMainBundle:Games:state }

games_join:
    pattern: /games/{game}/join
    defaults: { _controller: MyMainBundle:Games:join }

games_leave:
    pattern: /games/{game}/leave
    defaults: { _controller: MyMainBundle:Games:leave }


command_fleet_create:
    pattern: /commands/createfleet/{base}
    defaults: { _controller: MyMainBundle:Commands:createFleet }
